"""Render a Markdown report on DUF/PUF examples shared with sibling Mechs."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from dufmech.cross_mech import PROTEIN_TRAITS_MECH
from dufmech.cross_mech_snapshot import CROSS_MECH_DIR, CROSS_MECH_STEM
from dufmech.report import ReportError, latest_snapshot_path, load_json_rows, verified_manifest

REPORTS_DIR = Path("docs/reports")
TOP_N = 15


def render_cross_mech_report(
    rows: list[Mapping[str, Any]], manifest: Mapping[str, Any], *, top_n: int = TOP_N
) -> str:
    """Return a deterministic Markdown report for one cross-Mech snapshot."""

    snapshot = manifest["snapshot"]
    mechs = manifest["source"]["mechs"]
    ptm = [row for row in rows if row["source_mech"] == PROTEIN_TRAITS_MECH]
    curated = [row for row in rows if row["source_mech"] != PROTEIN_TRAITS_MECH]
    examples = [row for row in ptm if row["source_section"] == "canonical_examples"]
    trait_families = {row["pfam_id"] for row in ptm if row["source_section"] == "trait_identifier"}
    self_examples = {row["pfam_id"] for row in examples if row["family_mentioned_in_record"]}
    functional = [row for row in examples if row["source_category"].startswith("function/")]

    lines = [
        f"# DUF/PUF examples across Mechs ({snapshot['date']})",
        "",
        "<!-- Generated by scripts/cross_mech_report.py; do not edit by hand. -->",
        "",
        (f"Snapshot `{snapshot['id']}` against worklist "
        f"`{snapshot['input_snapshot_ids']['worklist']}`, reading every Mech at "
        f"`{snapshot['source_ref']}`."),
        "",
        ("Link bases: `record_mentions_*` means the record text names the family; "
        "`uniprot_pfam_xref` means a UniProtKB accession cited by the record carries the "
        "family in UniProtKB; `canonical_example_family_classification` and "
        "`trait_identifier` come from ProteinTraitsMech's structured fields. A text "
        "mention says the family is discussed, not that a specific protein was curated."),
        "",
        "## Coverage by Mech",
        "",
        "| Mech | Commit | Records scanned | Rows | Families | Proteins |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for name, meta in sorted(mechs.items()):
        mech_rows = [row for row in rows if row["source_mech"] == name]
        lines.append(
            f"| {name} | `{meta['commit'][:10]}` | {meta['records_scanned']:,} | "
            f"{len(mech_rows):,} | {len(_families(mech_rows)):,} | "
            f"{len(_proteins(mech_rows)):,} |"
        )

    lines += [
        "",
        "## DUF examples curated outside ProteinTraitsMech",
        "",
        "These records are now carried in DUFMech's cross-Mech snapshot and dashboard.",
        "",
        "| Family | Status | Mech | Record | Protein | Basis |",
        "|---|---|---|---|---|---|",
    ]
    for row in curated:
        family = row["short_name"] + (f" ({row['pfam_id']})" if row["pfam_id"] else "")
        protein = (
            f"{row['uniprot_accession']} {row['protein_label']}".strip()
            if row["uniprot_accession"]
            else ""
        )
        lines.append(
            f"| {_cell(family)} | {row['unknown_status']} | {row['source_mech']} | "
            f"{_cell(row['source_record_label'] or row['source_record_id'])} | "
            f"{_cell(protein)} | {', '.join(row['link_basis'])} |"
        )

    unlisted = sorted({row["short_name"] for row in curated if not row["pfam_id"]})
    lines += [
        "",
        (f"{len(unlisted)} names do not match a current worklist short name: "
        f"{', '.join(unlisted) or 'none'}. DUF names here are usually families Pfam renamed "
        "after characterization; UPF names are UniProt nomenclature, which the Pfam-derived "
        "worklist never carries. Both need a Pfam ID before DUFMech can score them."),
        "",
        "## ProteinTraitsMech",
        "",
        (f"- {len(trait_families):,} of {manifest['rows']['unique_pfam_ids']:,} linked "
        "families have a ProteinTraitsMech trait record."),
        (f"- {len(self_examples):,} of those trait records list a canonical example that "
        f"carries the family; {len(trait_families - self_examples):,} do not."),
        (f"- {len(examples):,} canonical-example rows place {len(_proteins(examples)):,} "
        f"DUF-carrying proteins under {len(_families(examples)):,} families."),
        (f"- {len(functional):,} of those rows sit under functional traits "
        f"({len(_proteins(functional)):,} proteins, {len(_families(functional)):,} families)."),
        "",
        "| Functional trait category | Rows | Proteins | Families |",
        "|---|---:|---:|---:|",
    ]
    by_category: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for row in functional:
        by_category[row["source_category"]].append(row)
    for category, group in sorted(by_category.items()):
        lines.append(
            f"| {category} | {len(group):,} | {len(_proteins(group)):,} | "
            f"{len(_families(group)):,} |"
        )

    lines += _reuse_sections(curated, examples, functional, top_n)
    return "\n".join(lines) + "\n"


def _reuse_sections(
    curated: list[Mapping[str, Any]],
    examples: list[Mapping[str, Any]],
    functional: list[Mapping[str, Any]],
    top_n: int,
) -> list[str]:
    lines = ["", "## Reuse candidates", ""]
    examples_by_family: dict[str, list[Mapping[str, Any]]] = defaultdict(list)
    for row in examples:
        examples_by_family[row["pfam_id"]].append(row)

    trait_rows = [row for row in curated if row["source_mech"] == "TraitMech" and row["pfam_id"]]
    trait_families = sorted(
        {row["pfam_id"] for row in trait_rows if row["source_section"] == "record_text"}
    )
    lines += [
        "### TraitMech",
        "",
        ("Families named in TraitMech records, with proteins that could supply an example: "
        "UniProtKB accessions already cited by TraitMech, then ProteinTraitsMech canonical "
        "examples."),
        "",
        "| Family | TraitMech proteins | ProteinTraitsMech example proteins |",
        "|---|---|---|",
    ]
    for pfam_id in trait_families:
        own = _protein_list(
            [row for row in trait_rows if row["pfam_id"] == pfam_id and row["uniprot_accession"]],
            limit=3,
        )
        proteins = _protein_list(examples_by_family.get(pfam_id, []), limit=3)
        gap = "none; needs a DUFMech member example" if not own else ""
        lines.append(f"| {pfam_id} | {own} | {proteins or gap} |")

    cited = {(row["pfam_id"], row["uniprot_accession"]) for row in examples}
    missing = sorted(
        {
            (row["pfam_id"], row["short_name"], row["uniprot_accession"], row["protein_label"],
             row["source_mech"])
            for row in curated
            if row["uniprot_accession"] and (row["pfam_id"], row["uniprot_accession"]) not in cited
        }
    )
    lines += [
        "",
        "### ProteinTraitsMech",
        "",
        ("DUF proteins cited in other Mechs that are not canonical examples anywhere in "
        "ProteinTraitsMech:"),
        "",
        "| Family | Protein | Cited in |",
        "|---|---|---|",
    ]
    lines += [
        f"| {short} ({pfam}) | {acc} {_cell(label)} | {mech} |"
        for pfam, short, acc, label, mech in missing
    ] or ["| none | | |"]

    natural_product_words = ("biosynth", "antibiotic", "toxin", "secondary metabol")
    for title, scope, matches in (
        (
            "NaturalProductMech and AntibioticMech",
            ("functional traits whose label mentions biosynthesis, antibiotics, toxins, or "
            "secondary metabolism"),
            [
                row for row in functional
                if any(word in row["source_record_label"].lower() for word in natural_product_words)
            ],
        ),
        (
            "PathwayMech",
            "GO biological-process (pathway) traits",
            [row for row in functional if row["source_category"].startswith("function/pathway")],
        ),
    ):
        lines += [
            "",
            f"### {title}",
            "",
            (f"DUF proteins under ProteinTraitsMech {scope} "
            f"({len(_proteins(matches)):,} proteins; top {top_n} traits by protein count):"),
            "",
            "| Trait | DUF families | Example proteins |",
            "|---|---|---|",
        ]
        by_trait: dict[tuple[str, str], list[Mapping[str, Any]]] = defaultdict(list)
        for row in matches:
            by_trait[(row["source_record_id"], row["source_record_label"])].append(row)
        ranked = sorted(by_trait.items(), key=lambda item: (-len(_proteins(item[1])), item[0]))
        for (trait_id, label), group in ranked[:top_n]:
            families = ", ".join(sorted({row["short_name"] for row in group}))
            lines.append(
                f"| {trait_id} {_cell(label)} | {families} | {_protein_list(group, limit=3)} |"
            )

    reviewed_by_taxon: dict[str, set[str]] = defaultdict(set)
    for row in examples:
        if row["reviewed"] is True and row["taxon_label"]:
            reviewed_by_taxon[row["taxon_label"]].add(row["uniprot_accession"])
    lines += [
        "",
        "### TaxonMech",
        "",
        (f"Reviewed DUF example proteins come from {len(reviewed_by_taxon):,} taxa. The most "
         "frequent could anchor DUF-protein links on TaxonMech taxon records:"),
        "",
        "| Taxon | Reviewed DUF example proteins |",
        "|---|---:|",
    ]
    ranked_taxa = sorted(reviewed_by_taxon.items(), key=lambda item: (-len(item[1]), item[0]))
    for taxon, proteins in ranked_taxa[:top_n]:
        lines.append(f"| {_cell(taxon)} | {len(proteins):,} |")
    return lines


def _protein_list(rows: Iterable[Mapping[str, Any]], *, limit: int) -> str:
    seen: dict[str, Mapping[str, Any]] = {}
    for row in sorted(rows, key=lambda row: (row["reviewed"] is not True, row["uniprot_accession"])):
        seen.setdefault(row["uniprot_accession"], row)
    items = [
        f"{accession}{'' if row['reviewed'] else ' (unreviewed)'}"
        for accession, row in list(seen.items())[:limit]
    ]
    if len(seen) > limit:
        items.append(f"+{len(seen) - limit} more")
    return ", ".join(items)


def _families(rows: Iterable[Mapping[str, Any]]) -> set[str]:
    return {row["pfam_id"] or row["short_name"] for row in rows}


def _proteins(rows: Iterable[Mapping[str, Any]]) -> set[str]:
    return {row["uniprot_accession"] for row in rows if row["uniprot_accession"]}


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cross-mech-dir", type=Path, default=CROSS_MECH_DIR)
    parser.add_argument("--out-dir", type=Path, default=REPORTS_DIR)
    parser.add_argument("--check", action="store_true", help="fail if the report is stale")
    args = parser.parse_args(argv)
    try:
        path = latest_snapshot_path(args.cross_mech_dir, CROSS_MECH_STEM)
        assert path is not None
        manifest = verified_manifest(path)
        text = render_cross_mech_report(list(load_json_rows(path)), manifest)
    except (ReportError, KeyError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    target = args.out_dir / f"{path.stem}.md"
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != text:
            print(f"{target} is stale; run `just cross-mech-report`", file=sys.stderr)
            return 1
        print(f"{target} is current")
        return 0
    args.out_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
