"""Keep README corpus statistics aligned with frozen DUFMech snapshots."""

from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from dufmech.report import build_report, load_latest_rows

BEGIN = "<!-- BEGIN GENERATED CORPUS STATS -->"
END = "<!-- END GENERATED CORPUS STATS -->"


class DocsError(RuntimeError):
    """Raised when generated documentation cannot be updated."""


def render_current_corpus_block(
    report: Mapping[str, Any],
    *,
    input_ids: Mapping[str, str],
) -> str:
    """Render the README current-corpus block."""

    families = _mapping(report.get("families"))
    status_rows = _mapping(report.get("by_unknown_status"))
    characterization_rows = _mapping(report.get("by_characterization_status"))
    candidate_rows = _mapping(report.get("by_candidate_reason"))
    demotion_rows = _mapping(report.get("by_demotion_reason"))

    lines = [
        BEGIN,
        "<!-- Generated by scripts/check_docs.py; do not edit this block by hand. -->",
        (
            f"**{_int(families.get('total')):,} DUF/Pfam families** are "
            "currently committed from frozen InterPro/Pfam snapshots."
        ),
        "",
        (
            f"{_int(families.get('with_interpro_id')):,} carry InterPro IDs, "
            f"{_int(families.get('with_structures')):,} have InterPro structure "
            "counters, and "
            f"{_int(families.get('with_alphafold_models')):,} have AlphaFold DB "
            "model counters."
        ),
        "",
        f"Latest inputs: {', '.join(f'`{key}={value}`' for key, value in sorted(input_ids.items()))}.",
    ]

    lines.extend(_counter_table("Unknown-function seed status", status_rows))
    lines.extend(_counter_table("Characterization status", characterization_rows))
    lines.extend(_counter_table("Candidate reasons", candidate_rows))
    lines.extend(_counter_table("Demotion reasons", demotion_rows))
    lines.append(END)
    return "\n".join(lines)


def replace_current_corpus_block(text: str, block: str) -> str:
    """Replace the generated README corpus block."""

    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        raise DocsError(f"README.md has no {BEGIN} ... {END} block")
    return pattern.sub(lambda _match: block, text)


def render_block_from_paths(
    *,
    worklists_dir: Path = Path("data/worklists"),
    worklist_json: Path | None = None,
    score_json: Path | None = None,
) -> str:
    """Load frozen snapshots and render the README block."""

    worklist_rows, score_rows, input_ids = load_latest_rows(
        worklists_dir,
        worklist_json=worklist_json,
        score_json=score_json,
    )
    return render_current_corpus_block(
        build_report(worklist_rows, score_rows),
        input_ids=input_ids,
    )


def check_or_write_readme(
    readme: Path,
    *,
    block: str,
    write: bool,
) -> bool:
    """Check or write a README block; return true when the README is current."""

    text = readme.read_text(encoding="utf-8")
    new_text = replace_current_corpus_block(text, block)
    if write:
        readme.write_text(new_text, encoding="utf-8")
        return True
    return new_text == text


def _counter_table(title: str, rows: Mapping[str, Any]) -> list[str]:
    if not rows:
        return []
    lines = [
        "",
        f"**{title}**",
        "",
        "| Value | Families |",
        "|---|---:|",
    ]
    for key, value in rows.items():
        lines.append(f"| `{key}` | {_int(value):,} |")
    return lines


def _int(value: object) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    return 0


def _mapping(value: object) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}
